### ISSUE TITLE
Replace `fast-glob` with `tinyglobby` in Vite

### ISSUE THREAD

**Issue by benmccann** [es-tooling/ecosystem-cleanup#106]
I can offer a code review for this one and @bluwy also mentioned being supportive of the idea. It would be a good idea to do somewhat soon while 6.0 is in pre-release so that we can do it as part of a major release. Vitest, vitepress, vite-plugin-pwa, and other Vite-affiliated projects have already moved

See https://github.com/SuperchupuDev/tinyglobby/issues/28 for additional details on migrating

**Comment by bluwy** [comment]
It would be best if we check with the Vite maintainers first, maybe in it's server's contributing channel. I don't have the final say for changes like this.

**Comment by ziebam** [comment]
I've started some work on this locally, waiting for further discussion with `vite` maintainers and `tinyglobby` dependencies before pushing though.

**Comment by benmccann** [comment]
Confirmed on the Vite Discord that other maintainers are also supportive. They pointed out though that we'd also need to migrate `@rollup/plugin-dynamic-import-vars` to get the full benefit, so I've filed an issue for it as well: https://github.com/es-tooling/ecosystem-cleanup/issues/109

**Comment by benmccann** [comment]
I've sent a PR to switch `@rollup/plugin-dynamic-import-vars` to `tinyglobby`

**Comment by ziebam** [comment]
@benmccann We caught a bug on 0.2.7 while migrating to `tinyglobby` in Vite, make sure to bump the version to 0.2.8 in your `@rollup/plugin-dynamic-import-vars` PR too.

`https://github.com/vitejs/vite/pull/18243` – migration in Vite itself.

**Comment by benmccann** [comment]
Thanks. Updated!

**Comment by benmccann** [comment]
completed in https://github.com/vitejs/vite/pull/18243
