### ISSUE TITLE
Replace fast-glob with alternative in vitepress

### ISSUE THREAD

**Issue by 43081j** [es-tooling/ecosystem-cleanup#42]
vitepress uses fast-glob as a dev dependency.

https://github.com/vuejs/vitepress

Two possible alternatives which are leaner and faster:

- [tiny-glob](https://github.com/terkelg/tiny-glob)
- [fdir](https://github.com/thecodrr/fdir/)

**Comment by ziebam** [comment]
We can close this as the PR got merged 2 days ago.
