### ISSUE TITLE
Remove is-builtin-module from rollup

### ISSUE THREAD

**Issue by 43081j** [es-tooling/ecosystem-cleanup#49]
rollup uses `is-builtin-module` here:
https://github.com/rollup/plugins/blob/9e7f576f33e26d65e9f2221d248a2e000923e03f/packages/node-resolve/src/index.js#L193

it has an engine constraint of `>=14` which means we can't use `isBuiltin` from node itself.

however, we can use `builtinModules` with a simple string replace:

```ts
import {builtinModules} from 'node:module';

const name = '...';
builtinModules.includes(name.replace('node:', ''));
```

**Comment by 43081j** [comment]
tracked in rollup/plugins#1735

**Comment by MichaelDeBoey** [comment]
https://github.com/rollup/plugins/pull/1735 is now merged
