### ISSUE TITLE
Add a labeling system to easily find work that hasn't been picked yet

### ISSUE THREAD

**Issue by mehulkar** [es-tooling/ecosystem-cleanup#52]
When I come to this repo, I sometimes find it hard to find an untouched issue. It would be great to use labels to filter out the ones that already have something.

(I'm happy to help, but it looks like on personal repos you can't [limit access to just issue triage](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository). Happy to get collab access if you're comfortable with it though

**Comment by 43081j** [comment]
for sure we should do this

i've been slacking lately on making new issues too while i finish the storybook changes, so help would be appreciated

im thinking of transferring the repo to an org where a few of us are storing related repos too (yet to be announced, hopefully this week). meanwhile, ill at least sort the existing issues though and have a think about how best to setup permissions

probably will end up just adding you as a collaborator but will let you know

**Comment by mehulkar** [comment]
happy to wait for the org setup too!
