### ISSUE TITLE
Replace `execa` in `vitest`

### ISSUE THREAD

**Issue by benmccann** [es-tooling/ecosystem-cleanup#57]
`execa` pulls in quite a few dependencies and `vitest` is heavily used - especially among this community

**Comment by benmccann** [comment]
Here's what astro did as an alternative:

https://github.com/withastro/astro/blob/main/packages/create-astro/src/shell.ts

**Comment by AbhiPrasad** [comment]
I think the windows support + error handling makes this pretty hard to replace for a lot of users.

Looking at the [dep graph](https://npmgraph.js.org/?q=execa), there is probably a good opportunity to modernize [node-cross-spawn](https://github.com/moxystudio/node-cross-spawn) though.

**Comment by 43081j** [comment]
in the tinylibs org we're also working on a lighter alternative, but isn't quite ready yet just FYI

**Comment by TheDevMinerTV** [comment]
```
Package size report
===================

Package info for "vitest@2.0.3": 33 MB
  Released: 2024-07-15 10:03:50.134 +0000 UTC (1d ago)
  Downloads last week: 46,096 (0.89%)
  Estimated traffic last week: 1.5 TB
  Subdependencies: 101

Removed dependencies:
  - execa@8.0.1: 308 kB (0.94%)
    Downloads last week: 11,322,011 (13.88%)
    Downloads last week from "vitest@2.0.3": 46,096 (0.41%)
    Estimated traffic last week: 3.5 TB
    Estimated traffic from "vitest@2.0.3": 14 GB (0.41%)
    Subdependencies: 18 (17.82%)

(didn't calculate in new dependencies)

Estimated package size: 33 MB → 32 MB (99.06%)
Estimated traffic over a week: 1.5 TB → 1.5 TB (14 GB saved)
Estimated traffic over a week @ 100% downloads: 170 TB → 168 TB (1.6 TB saved)
```

**Comment by 43081j** [comment]
tinyexec now exists too which could slot in nicely

Worth taking a look

**Comment by benmccann** [comment]
There is agreement to use `tinyexec` if anyone would like to take a stab at it: https://github.com/vitest-dev/vitest/pull/5713

**Comment by ziebam** [comment]
Submitted a PR for this change: https://github.com/vitest-dev/vitest/pull/6454.

**Comment by TheDevMinerTV** [comment]
> Submitted a PR for this change: [vitest-dev/vitest#6454](https://github.com/vitest-dev/vitest/pull/6454).

Merged ˆ

**Comment by benmccann** [comment]
Woohoo!
