### ISSUE TITLE
Replace `ora` in eslint-plugin-file-progress

### ISSUE THREAD

**Issue by 43081j** [es-tooling/ecosystem-cleanup#72]
We can replace `ora` with an alternative (see #71)

current npmgraph:
https://npmgraph.js.org/?q=eslint-plugin-file-progress

current size: 580K

you also have the opportunity to replace `chalk` with `picocolors` while you're in there (or in a separate PR) and reduce the footprint even further (plus improve perf)

**Comment by babs20** [comment]
I am going to put in a PR for this shortly. Removing `chalk` and `ora` in favor of `picocolors` and `nanospinner`.

**Comment by babs20** [comment]
[PR Here](https://github.com/sibiraj-s/eslint-plugin-file-progress/pull/6)

**Comment by 43081j** [comment]
great work 🥳 

let me know if/when they merge and we can close this

**Comment by babs20** [comment]
this has been merged!
