### ISSUE TITLE
Replace `cli-color` in `json-schema-to-typescript`

### ISSUE THREAD

**Issue by benmccann** [es-tooling/ecosystem-cleanup#79]
Depends on a new version of `picocolors` being published with bright variants. The code has been committed, but latest [picocolors](https://www.npmjs.com/package/picocolors) but not yet released as of the latest version: 1.0.1 .

**Comment by 43081j** [comment]
Sounds like he will be releasing a new version once the web pack problem is fixed

I'll chase up on that again
