### ISSUE TITLE
Replace ReadableStream in pino and pino-pretty

### ISSUE THREAD

**Issue by benmccann** [es-tooling/ecosystem-cleanup#80]
Can probably use a pass through stream instead

**Comment by 43081j** [comment]
looks like in pino-pretty, readable-stream and pump are used to make a transform stream:

https://github.com/pinojs/pino-pretty/blob/fc408ee1b4cc81f62adb361eeada32b09810414f/index.js#L146-L153

maybe you could just use a `Transform` stream? like `new Transform({transform: someFn})`

**Comment by benmccann** [comment]
I've sent a PR for this
