### ISSUE TITLE
Migrate postcss mixins to tinyglobby 

### ISSUE THREAD

**Issue by benmccann** [es-tooling/ecosystem-cleanup#99]
https://github.com/postcss/postcss-mixins/blob/dcbde522bde503c45489f608fb356b51299bac1d/package.json#L38

**Comment by ziebam** [comment]
Worth noting here that `postcss-mixins` is CommonJS-only, so requires a bit more effort than expected – either supporting CJS in `tinyglobby` or rewriting the plugin to ESM which the author might not be happy with.
